services:
  backend:
    build:
      context: ./src/backend
      dockerfile: ../../.docker/backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:8080
    volumes:
      - ./src/backend:/app
      - ./src/openapi/docs/message-service-api.yaml:/openapi/index.yaml
    command: air -c .air.toml
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/botgo.mod?authSource=admin
      - MONGODB_NAME=discord_bot
      - SERVER_ADDRESS=:8080
      - TZ=Asia/Tokyo

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
      - ME_CONFIG_BASEPATH_USERNAME=${MONGO_EXPRESS_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_BASICAUTH_PASSWORD}
    depends_on:
      - mongo

  redoc:
    image: redocly/redoc:v2.0.0
    environment:
      SPEC_URL: index.yaml
      PORT: 8081
      REDOC_OPTIONS: path-in-middle-panel="true"
    ports:
      - ${REDOC_PORT}:8081
    volumes:
      - ./src/openapi:/usr/share/nginx/html
    depends_on:
      - merger

  merger:
    build:
      context: ./src/openapi
      dockerfile: ../.././.docker/openapi/Dockerfile
    tty: true
    init: true
    command: >
      watch 'swagger-merger -i /openapi/docs/*.yaml -o /openapi/index.yaml; redocly build-docs /openapi/index.yaml -o /openapi/index.html' /openapi/docs
    volumes:
      - ./src/openapi:/openapi

volumes:
  mongo_data:
