FROM golang:1.22.0-alpine

WORKDIR /app

# 必要なパッケージのインストール
RUN apk add --no-cache gcc musl-dev

# 依存関係のコピーとダウンロード
COPY src/backend/go.mod src/backend/go.sum ./
RUN go mod download

# ソースコードのコピー
COPY src/backend ./

# テストの実行
CMD ["go", "test", "-v", "./..."]