linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - deadcode
    - gosec

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  deadcode:
    skip-files:
      - "*_test.go"

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - third_party/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
